#!/usr/bin/env bash

if [[ $# -eq 0 ]] ; then
  echo "" | \
    rofi -dmenu rofi -theme-str '#mainbox { children: [ "inputbar" ]; }' -p "Google:" | \
    xargs -I{} xdg-open https://duckduckgo.com/?q={}
else
 xdg-open https://duckduckgo.com/?q="$1"
fi
