#!/usr/bin/env bash

flake="$HOME/Ooo"

if [[ $# -eq 0 ]] ; then
  nh os boot "$flake" -H jake
else
  # --use-substitutes: copy directly from caches to host instead of through invocation host (i.e. laptop)
  nh os boot "$flake" -H "$1" --target-host root@"$1" # --use-substitutes
fi
