[audio]
sound_volume = 0.99999997764825821

[bar.default]
center = [ "media", "spacer_1", "clock" ]
compositor_blur = false
concave_edge_corners = false
end = [ "tray", "input_volume", "group:g1", "ram", "battery", "control-center" ]
margin_ends = 11
radius = 40
radius_top_left = 0
radius_top_right = 0
start = [ "launcher", "workspaces" ]
widget_spacing = 10

    [bar.default.dead_zone.actions]
    middle = "settings-open"

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "end"
    border_width = 1.0
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "notifications", "clipboard", "bluetooth", "volume", "brightness", "nightlight", "network" ]
    opacity = 1.0
    padding = 6.0

[battery]
warning_threshold = 20

[brightness]
minimum_brightness = 0.0099999997764825821

[calendar]
enabled = true

    [calendar.account.personal_google]
    name = "Google - Personal"
    type = "google"

[control_center]
hidden_tabs = [ "weather", "screen-time" ]
sidebar = "full"
sidebar_section = "full"

    [control_center.calendar]
    show_week_numbers = true

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "caffeine"

[desktop_widgets]
enabled = false
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "screen-off", "lock", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 660.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = false
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 600.0

[lockscreen]
blurred_desktop = true
fingerprint = false
transition_duration = 500

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 800.0
    cy = 708.0
    output = "eDP-1"
    placement_height = 900.0
    placement_width = 1600.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 144.0
    box_width = 272.0
    cx = 800.0
    cy = 298.0
    output = "eDP-1"
    placement_height = 900.0
    placement_width = 1600.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = true
        clock_style = "digital"
        font_family = "Atkinson Hyperlegible Next ExtraBold"
        shadow = true

[nightlight]
temperature_night = 2900

[osd]
hide_delay_ms = 1600

[shell]
launch_apps_as_systemd_services = true
password_style = "default"
polkit_agent = true

    [shell.animation]
    speed = 2.0000000298023224

    [shell.launcher]
    categories = false

        [shell.launcher.providers.emoji]
        prefix = "/"

        [shell.launcher.providers.session]
        prefix = ":"

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_session = true

    [shell.screenshot]
    directory = "/home/vic/personal/Pictures/screenshots"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Rosé Pine"
mode = "dark"
source = "builtin"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "kcolorscheme", "niri", "qt" ]
    community_ids = [
        "zen-browser",
        "discord",
        "gimp",
        "libreoffice",
        "neovim",
        "prismlauncher",
        "obs",
        "thunderbird",
        "papirus-icons",
        "bat"
    ]

        [theme.templates.user.nvim_base16]
        input_path = "~/.config/nvim/lua/matugen-template.lua"
        output_path = "~/.config/nvim/lua/matugen.lua"
        post_hook = "pkill -SIGUSR1 nvim"

[wallpaper]
directory = "/home/vic/personal/Pictures/wallpapers"
enabled = true

    [wallpaper.default]
    path = "/home/vic/personal/Pictures/wallpapers/cats.jpg"

    [wallpaper.last]
    path = "/home/vic/personal/Pictures/wallpapers/cats.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/vic/personal/Pictures/wallpapers/cats.jpg"

    [[wallpaper.favorite]]
    builtin_palette = "Rosé Pine"
    palette_source = "builtin"
    path = "/home/vic/personal/Pictures/wallpapers/cats.jpg"
    theme_mode = "dark"

[weather]
enabled = false

[widget.battery.actions]
right = "power-cycle"

[widget.bluetooth]
hide_when_no_connected_device = false

[widget.brightness]
show_label = false

[widget.clock]
anchor = true
format = "{:%H:%M  %a %-d}"

[widget.control-center]
color = "primary"

    [widget.control-center.actions]
    right = "panel-toggle session"

[widget.input_volume]
hide_when_inactive = true
show_label = false

[widget.launcher]
color = "primary"
glyph = "snowflake"

    [widget.launcher.actions]
    right = "dpms-off"

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

    [widget.media.actions]
    scroll_down = "volume-down"
    scroll_up = "volume-up"

[widget.network]
show_label = false

[widget.nightlight]
color = "on_surface"

    [widget.nightlight.actions]
    left = "nightlight-force-toggle"

[widget.ram]
highlight_color = "on_surface"
stat = "ram_pct"
visualization = "none"

    [widget.ram.actions]
    right = "exec ghostty +new-window --title=btop-window -e btop"

[widget.session]
color = "error"

[widget.spacer_1]
length = 125
type = "spacer"

[widget.tray]
capsule = true
capsule_border = "outline"
hide_passive = false

[widget.volume]
show_label = false

    [widget.volume.actions]
    scroll_down = "volume-down 2"
    scroll_up = "volume-up 2"

[widget.workspaces]
hide_when_empty = true
show_all_outputs = true
show_tooltip = false
