return {
	--  -- I purely use this plugin for the popup command line
	-- {
	-- 	"folke/noice.nvim",
	-- 	event = "VeryLazy",
	-- 	dependencies = { "MunifTanjim/nui.nvim" },
	-- 	opts = {
	-- 		messages = { enabled = false },
	-- 		popupmenu = { enabled = false },
	-- 		notify = { enabled = false },
	-- 		lsp = {
	-- 			progress = { enabled = false },
	-- 			hover = { enabled = false },
	-- 			signature = { enabled = false },
	-- 			message = { enabled = false },
	-- 		},
	-- 		health = { checker = false },
	-- 		presets = {
	-- 			bottom_search = true, -- use a classic bottom cmdline for search
	-- 			command_palette = true, -- position the cmdline and popupmenu together
	-- 		},
	-- 		views = {
	-- 			cmdline_popup = {
	-- 				position = { row = "95%", col = "50%" },
	-- 				size = { width = 60, height = "auto" },
	-- 			},
	-- 		},
	-- 	},
	-- },
}
